### PR TITLE
Conceal api_key by default in logs and production environment

### LINKED ISSUE #228: Conceal api_key in logs
The Rails log prints the API KEY send by authorities (Decidim Election module), should it be concealed same way as passwords?
```
bulletin_1  | D, [2021-11-12T09:48:12.651742 #7] DEBUG -- : [05dc3b0e-8b2f-4263-a323-76a8aaf7a640]   Authority Load (0.6ms)  SELECT "clients".* FROM "clients" WHERE "clients"."type" = $1 AND "clients"."unique_id" = $2 AND "clients"."api_key" = $3 LIMIT $4  [["type", "Authority"], ["unique_id", "electionsaudit"], ["api_key", "A2s4e52tqKV09IXDzVQc7aE1LKxWnRTuHJLskjiRSarwHwzStez9ELp8BVfhY95R4ySXdwNzE2Sjb6WAD4opCuWBqC6VM0pHyZwfitfmk8cX8eRoPh95ssDHs2QQQFyj"], ["LIMIT", 1]]
```

### PR DESCRIPTION
**Pull request by microstudi**
fixes #228 

This PR adds to the filter_parameters the attribute `api_key` although this do not prevent to show the value of the api key when displaying logs from ActiveRecord (sql queries).

In order to prevent SQL queries to be shown in the log, the most common way to do it is just to set up a logging level upper than `debug`.

### CODE REVIEW

**Comment by andreslucena** [comment]
@microstudi we should first finish with #284 so CI is green

**Comment by andreslucena** [comment]
@microstudi the build is green again, can you merge this branch with develop? If you can't or don't have the time, I can retake this.

**Comment by microstudi** [comment]
merged!

**Review by ahukkanen — APPROVED** [review]
:+1: 

I just merged with develop once more to be sure. I'll merge this once once CI shows green.

**Pull request merged**
