### PR TITLE
Upgrade Rails 7.0 in server

### PR DESCRIPTION
**Pull request by alecslupu**
This PR updates the Rails server version to Rails 7.0.4

### CODE REVIEW

**Review by andreslucena — CHANGES_REQUESTED** [review]
Tried the application locally and seems to work. Also, the test suite is green so it should work well. 

I'd change just two small details, to be better aligned to the Rails upgrade guide: 

1.  [Setter config.autoloader= has been deleted:](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#the-setter-config-autoloader-has-been-deleted)

I think it'd be better to just remove this comment (and the previous line too)
 https://github.com/alecslupu-pfa/decidim-bulletin-board/blob/b82d4c3405773f9731ae395d308191c1fe90d3ab/bulletin_board/server/config/application.rb#L24
 
2. [Use Spring > 2.0](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0-spring)

> If your application uses Spring, it needs to be upgraded to at least version 3.0.0.

According to the `Gemfile.lock` we're still on 2.1

https://github.com/alecslupu-pfa/decidim-bulletin-board/blob/b82d4c3405773f9731ae395d308191c1fe90d3ab/bulletin_board/server/Gemfile.lock#L371


---
Can you handle those so we can merge this? Thanks!

**Comment by andreslucena** [comment]
3. Update docs.

I found a small changes to make
https://github.com/decidim/decidim-bulletin-board/blob/develop/docs/modules/develop/pages/environment.adoc

And in these other files, I'd drop the version entirely: 

- docs/modules/develop/pages/c4_container.adoc 
- docs/modules/develop/pages/c4_component.adoc

**Comment by paarals** [comment]
check in todays meeting with @andreslucena

**Comment by alecslupu** [comment]
> check in todays meeting with @andreslucena 

@paarals I think i have the branch on my local... If you need something let me know

**Comment by paarals** [comment]
hi @alecslupu, this issue is not under our current contract, but if you have work done and we have enough time in the end of the contract that is likely possible (this desember), it would be very nice to add and complete it :-)

**Pull request closed without merging**
